home/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import *
app_name = 'home'

urlpatterns = [
    path('', login_required(HomeView.as_view()), name='home'),
    path('register/', RegisterView.as_view(), name='register'),
    path('super_user/', HomeAdminView.as_view(), name='super_admin')
]

product/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *
app_name = 'product'

urlpatterns = [
    path('product_name_read/', login_required(ProductRead.as_view()), name = 'product_read'),
    path('product_name_create/', login_required(ProductCreate.as_view()), name = 'product_create'),
    path('product_name_update/<int:pk>/', login_required(ProductUpdate.as_view()), name = 'product_update'),
    path('product_name_delete/<int:pk>/', login_required(ProductDelete.as_view()), name = 'product_delete'),
    path('product_type_read/', login_required(ProductTypeRead.as_view()), name = 'product_type_read'),
    path('product_type_create/', login_required(ProductTypeCreate.as_view()), name = 'product_type_create'),
    path('product_type_update/<int:pk>/', login_required(ProductTypeUpdate.as_view()), name = 'product_type_update'),
    path('product_type_delete/<int:pk>/', login_required(ProductTypeDelete.as_view()), name = 'product_type_delete'),
] 

src/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'), name='home'),
    path('product/', include('product.urls'), name='product'),
    path('sales/', include('sales.urls'), name='sales'),
    path('receipts/', include('receipts.urls'), name='receipts'),
    path('accounts/', include('django.contrib.auth.urls'))
]

product/models.py
from django.db import models

# Create your models here.
class ProductType(models.Model):
    name = models.CharField(max_length = 40, null = False, unique = True)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default = True)
    
    def __str__(self) -> str:
        return self.name
    
class ProductName(models.Model):
    name = models.CharField(max_length = 40, null = False, unique = True)
    price = models.FloatField(null = False)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default = True)
    type = models.ForeignKey(ProductType, null=True, blank=True, on_delete=models.CASCADE)
    
    def __str__(self) -> str:
        return self.name

product/forms.py
from django import forms

from .models import ProductName
from .models import ProductType

class ProductNameForm(forms.ModelForm):
    class Meta:
        model = ProductName
        fields = [
            'name',
            'price',
            'type'
        ]
        labels = {
            'name' : 'nombre del producto',
            'price' : 'precio del producto',
            'type' : 'tipo de producto'
        }

class ProductTypeForm(forms.ModelForm):
    class Meta:
        model = ProductType
        fields = [
            'name',
        ]
        labels = {
            'name' : 'nombre del type de producto',
        }
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input',
                    'placeholder': ''
                }
            ),
        }
        

product/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import ListView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from django.contrib.auth.mixins import UserPassesTestMixin

from .models import ProductName
from .models import ProductType

from .forms import ProductNameForm
from .forms import ProductTypeForm

# Create your views here.

#CRUD product_type
class ProductTypeCreate(UserPassesTestMixin, CreateView):
    model = ProductType
    form_class = ProductTypeForm
    template_name = 'product/table_product_type/product_type_form.html'
    success_url = reverse_lazy('product:product_type_read')
    
    def test_func(self):
        return self.request.user.is_staff

class ProductTypeRead(UserPassesTestMixin, ListView):
    model = ProductType
    template_name = 'product/table_product_type/product_type_read.html'
    
    def test_func(self):
        return self.request.user.is_staff

class ProductTypeUpdate(UserPassesTestMixin, UpdateView):
    model = ProductType
    form_class = ProductTypeForm
    template_name = 'product/table_product_type/product_type_form.html'
    success_url = reverse_lazy('product:product_type_read')
    
    def test_func(self):
        return self.request.user.is_staff

class ProductTypeDelete(UserPassesTestMixin, DeleteView):
    model = ProductType
    template_name = 'product/table_product_type/product_type_delete.html'
    success_url = reverse_lazy('product:product_type_read')
    
    def test_func(self):
        return self.request.user.is_staff

#CRUD product_name
class ProductCreate(UserPassesTestMixin, CreateView):
    model = ProductName
    form_class = ProductNameForm
    template_name = 'product/table_product_name/product_form.html'
    success_url = reverse_lazy('product:product_read')
    
    def test_func(self):
        return self.request.user.is_staff

class ProductRead(UserPassesTestMixin, ListView):
    model = ProductName
    template_name = 'product/table_product_name/product_read.html'
    
    def test_func(self):
        return self.request.user.is_staff

class ProductUpdate(UserPassesTestMixin, UpdateView):
    model = ProductName
    form_class = ProductNameForm
    template_name = 'product/table_product_name/product_form.html'
    success_url = reverse_lazy('product:product_read')
    
    def test_func(self):
        return self.request.user.is_staff

class ProductDelete(UserPassesTestMixin, DeleteView):
    model = ProductName
    template_name = 'product/table_product_name/product_delete.html'
    success_url = reverse_lazy('product:product_read')
    
    def test_func(self):
        return self.request.user.is_staff

product/templates/product/table_product_name/product_delete.html
{% extends 'home/home_admin.html' %}

{% load render_text %}
{% load render_table %}
{% load render_form %}
{% load render_button %}

{% block title%}{{ block.super }} Ordenes del pedido{% endblock %}

{% block main %}
<form method="POST">
    {% csrf_token %}
    <p>elminimar el producto {{ object.name }}?</p>
    <button type="submit">si, eliminiar</button>
    <a href="{% url 'product:product_read' %}">cancelar</a>
</form>
{% endblock %}

product/templates/product/table_product_name/product_form.html
<h1>create</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">submit</button>
</form>

product/templates/product/table_product_name/product_read.html
{% extends 'home/home_admin.html' %}

{% load render_text %}
{% load render_table %}
{% load render_form %}
{% load render_button %}

{% block title%}{{ block.super }} Ordenes del pedido{% endblock %}

{% block main %}
    <table>
        <thead>
            <tr>
                <td>nombre</td>
                <td>precio</td>
                <td>tipo</td>
                <td>options</td>
            </tr>
        </thead>
        <tbody>
            {% if object_list %}
            {% for product in object_list %}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ product.price }}</td>
                <td>{{product.type }}</td>
                <td><a href="{% url 'product:product_update' product.id %}">editar</a></td>
                <td><a href="{% url 'product:product_delete' product.id %}">eliminar</a></td>
            </tr>
            {% endfor %}
            {% endif %}
        </tbody>
    </table>
    <a href="{% url 'product:product_create' %}">crear nuevo producto</a>
    <br>
    <a href="{% url 'home:super_admin' %}">volver al inicio</a>
{% endblock %}