home/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import *
app_name = 'home'

urlpatterns = [
    path('', login_required(HomeView.as_view()), name='home'),
    path('register/', RegisterView.as_view(), name='register'),
    path('super_user/', HomeAdminView.as_view(), name='super_admin')
]

receipts/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import *
app_name = 'receipts'

urlpatterns = [
    path('pay_order/', login_required(PayOrder.as_view()), name='pay'),
    path('receipt_read/', login_required(ReceiptRead.as_view()), name='receipt_read'),
    path('receipt_all/<int:pk>', login_required(ReceiptAllView.as_view()), name='receipt_all'),
    path('receipt_delete/<int:pk>/', login_required(ReceiptDelete.as_view()), name='receipt_delete')
]

sales/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import *
app_name = 'sales'

urlpatterns = [
    path('add_to_cart_food/<int:pk>/', login_required(AddCart.as_view()), name='add_food'),
    path('add_to_card_soda/<int:pk>/', login_required(AddCart.as_view()), name='add_soda'),
    path('delete_order_to_cart/<int:pk>/', login_required(DeteleOrder.as_view()), name='delete_order'),
    path('clear_cart/', login_required(ClearCart.as_view()), name='clear_cart')
]

src/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'), name='home'),
    path('product/', include('product.urls'), name='product'),
    path('sales/', include('sales.urls'), name='sales'),
    path('receipts/', include('receipts.urls'), name='receipts'),
    path('accounts/', include('django.contrib.auth.urls'))
]

receipts/models.py
from django.db import models

# Create your models here.
class Clients(models.Model):
    name = models.CharField(max_length=25, null=False)
    nit = models.IntegerField(null=False, default=0)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default = True)

class Receipts(models.Model):
    sale_total = models.FloatField(null=False)
    received = models.FloatField(null=False)
    change = models.FloatField(null=False)
    client = models.ForeignKey(Clients, null=True, blank=True, on_delete=models.CASCADE)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default = True)

receipts/forms.py
from django import forms

from .models import Clients, Receipts

class FormClient(forms.ModelForm):
    class Meta:
        model = Clients
        fields = [
            'name', 'nit',
        ]
        labels = {
            'name' : 'ingrese el nombre del usuario',
            'nit' : 'ingrese el nit o ci del cliente',
        }
        widgets = {
            'nit': forms.NumberInput(
                attrs={
                    'value': '0',
                    'class': 'block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input',
                    'placeholder': 'Ingrese el nit del cliente'
                }
            ),
            'name' : forms.TextInput(
                attrs={
                    'class': 'block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input',
                    'placeholder': 'Ingrese el nombre del cliente'
                }
            )
        }

class FormReceipt(forms.ModelForm):
    class Meta:
        model = Receipts
        fields = [
            'received'
        ]
        labels = {
            'received' : 'ingrese monto que pago el cliente'
        }
        widgets = {
            'received': forms.TextInput(
                attrs={
                    'class': 'block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input',
                    'placeholder': 'Ingrese el pago en Bs'
                }
            ),
        }

class FormReceiptFilter(forms.Form):
    fecha = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'type': 'date',
                'class': 'block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input',
            }
        )
    )

receipts/views.py
from django.shortcuts import render
from django.shortcuts import redirect

from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin

from django.views import View
from django.views.generic import ListView
from django.views.generic import DeleteView

from django.urls import reverse_lazy

from .forms import FormClient
from .forms import FormReceipt
from .forms import FormReceiptFilter

from .models import Receipts

from .helper import HelperClients
from .helper import HelperReceipts

from src.create_pdf import CreatePdf
from src.helper import HelperApp
from sales.helper import HelperSale

# Create your views here.
class PayOrder(View):
    def get(self, request, *args, **kwarg):
        form_client = FormClient()
        form_received = FormReceipt()
        orders = HelperApp.get_order(request)
        orders = False if len(orders) == 0 else orders
        total = HelperApp.get_total(request) if orders else None
        context = {
            'form_client' : form_client,
            'form_received' : form_received,
            'orders' : orders,
            'total' : total
        }
        return render(request, 'receipts/view_orders.html', context, )
    
    def post(self, request, *args, **kwarg):
        form_client = FormClient(request.POST)
        form_received = FormReceipt(request.POST)
        if not (form_client.is_valid() and form_received.is_valid()):
            orders = HelperApp.get_order(request)
            orders = False if len(orders) == 0 else orders
            total = HelperApp.get_total(request) if orders else None
            context = {
                'form_client' : form_client,
                'form_received' : form_received,
                'orders' : orders,
                'total' : total
            }
            return render(request, 'receipts/view_orders.html', context, )
        
        client = HelperClients.search_client(form_client)
        if HelperClients.check_pay(request, form_received):
            received = HelperReceipts.save_receipt(request, form_received, client)
            sales_received = HelperSale.save_sales_receipts(request, received)
            CreatePdf.create_pdf(received, sales_received, client)
            messages.success(request, 'Venta guardada exitosamente')
            messages.success(request, 'Se mando a imprimir el ticket')
        return redirect('sales:clear_cart')
    
#Crud receipts
class ReceiptRead(UserPassesTestMixin, ListView):
    model = Receipts
    template_name = 'receipts/table_receipt.html'
    form_class = FormReceiptFilter
    
    def test_func(self):
        return self.request.user.is_staff
    
    def get_queryset(self):
        queryset = super().get_queryset()
        form = self.form_class(self.request.GET)

        if form.is_valid():
            fecha = form.cleaned_data['fecha']
            # Filtrar los objetos según la fecha proporcionada
            queryset = queryset.filter(create__date=fecha)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form_class(self.request.GET)
        return context

class ReceiptAllView(UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_staff
    
    def get(self, request, *args, **kwarg):
        receipt_id = self.kwargs['pk']
        receipt_all = HelperReceipts.get_receipt_all(receipt_id)
        context = {
            'receipts' : receipt_all,
        }
        return render(request, 'receipts/table_receipt_all.html', context)

class ReceiptDelete(UserPassesTestMixin, DeleteView):
    model = Receipts
    template_name = 'receipts/receipt_delete.html'
    success_url = reverse_lazy('receipts:receipt_read')
    
    def test_func(self):
        return self.request.user.is_staff
    
    def post(self, request, *args, **kwargs):
        messages.success(self.request, 'Recibo eliminado exitosamente.')
        return super().post(request, *args, **kwargs)

receipts/templates/receipts/receipt_delete.html
{% extends 'home/home_admin.html' %}

{% load render_text %}
{% load render_table %}
{% load render_form %}
{% load render_button %}

{% block title%}{{ block.super }} Ordenes del pedido{% endblock %}

{% block main %}
<form method="POST">
    {% csrf_token %}
    <p>elminimar el Recibo {{ object.id }}?</p>
    <button type="submit">si, eliminiar</button>
    <a href="{% url 'receipts:receipt_read' %}">cancelar</a>
</form>
{% endblock %}

receipts/templates/receipts/table_receipt.html
{% extends 'home/home_admin.html' %}

{% load render_text %}
{% load render_table %}
{% load render_form %}
{% load render_button %}

{% block title%}{{ block.super }} Ordenes del pedido{% endblock %}

{% block main %}
{% render_title 'filtar los recibos por fecha'%}

<form method="get" action="{% url 'receipts:receipt_read' %}">
    {% csrf_token %}
    {% render_input form.fecha %}
    {% render_button_form 'Filtar recibos'%}
</form>

<table>
    <thead>
        <tr>
            <td>Id recibo</td>
            <td>Venta total</td>
            <td>Recibido</td>
            <td>Cambio</td>
            <td>Cliente</td>
            <td>Fecha</td>
            <td>Recibo completo</td>
            <td>eliminar</td>
        </tr>
    </thead>
    <tbody>
        {% if object_list %}
        {% for receipts in object_list %}
        <tr>
            <td>{{receipts.id }}</td>
            <td>{{ receipts.sale_total }} Bs</td>
            <td>{{ receipts.received }} Bs</td>
            <td>{{receipts.change }} Bs</td>
            <td>{{receipts.client.name }}</td>
            <td>{{receipts.create}}</td>
            <td><a href="{% url 'receipts:receipt_all' receipts.id %}">Ver recibo total</a></td>
            <td><a href="{% url 'receipts:receipt_delete' receipts.id %}">eliminar</a></td>
            
        </tr>
        {% endfor %}
        {% endif %}
    </tbody>
</table>
<br>
<a href="{% url 'home:super_admin' %}">volver al inicio</a>
{% endblock %}

receipts/templates/receipts/table_receipt_all.html
{% extends 'home/home_admin.html' %}

{% load render_text %}
{% load render_table %}
{% load render_form %}
{% load render_button %}

{% block title%}{{ block.super }} Ordenes del pedido{% endblock %}

{% block main %}

{% render_title 'Datos del recibo' %}
<div class="w-full mb-8 overflow-hidden rounded-lg shadow-xs">
    <div class="w-full overflow-x-auto">
      <table class="w-full whitespace-no-wrap">
        <thead>
            {% render_thead '["Codigo del recibo", "Cliente", "Venta total", "Recivido", "Cambio"]' %}
        </thead>
        <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
          <tr class="text-gray-700 dark:text-gray-400">
            {% render_th receipts.0.receipt.id 'px-4 py-3 text-sm' %} 
            {% render_th receipts.0.receipt.client.name 'px-4 py-3 text-sm' %}
            {% render_th receipts.0.receipt.sale_total 'px-4 py-3 text-sm' %}
            {% render_th receipts.0.receipt.received 'px-4 py-3 text-sm' %}
            {% render_th receipts.0.receipt.change 'px-4 py-3 text-sm' %}
          </tr>
        </tbody>
      </table>
    </div>
</div>
<div class="w-full mb-8 overflow-hidden rounded-lg shadow-xs">
  <div class="w-full overflow-x-auto">
    <table class="w-full whitespace-no-wrap">
      <thead>
          {% render_thead '["Producto", "Cantidad", "Precio", "Precio total"]' %}
      </thead>
      <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">  
          {% for receipt in receipts%}
          <tr class="text-gray-700 dark:text-gray-400">
            {% render_th receipt.product.name 'px-4 py-3 text-sm' %} 
            {% render_th receipt.count 'px-4 py-3 text-sm' %}
            {% render_th receipt.price 'px-4 py-3 text-sm' %}
            {% render_th receipt.price_total 'px-4 py-3 text-sm' %}
          </tr>
          {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% render_button 'Volvel al inicio' 'home:super_admin' %}
{% endblock %}

receipts/templates/receipts/view_orders.html
{% extends 'home/home.html' %}

{% load render_text %}
{% load render_table %}
{% load render_form %}
{% load render_button %}

{% block title%}{{ block.super }} Ordenes del pedido{% endblock %}

{% block main %}

{% if orders %}
{% render_title 'Datos del recibo' %}
<div class="w-full mb-8 overflow-hidden rounded-lg shadow-xs">
    <div class="w-full overflow-x-auto">
      <table class="w-full whitespace-no-wrap">
        <thead>
            {% render_thead '["Producto", "Cantidad", "Precio unitario", "Precio total", "Eliminar"]' %}
        </thead>
        <tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
            {% render_tbody orders %}
            <tr class="text-gray-700 dark:text-gray-400">
                <th class="px-4 py-3 text-sm">Total de compra</th>
                <th class="px-4 py-3 text-sm"></th>
                <th class="px-4 py-3 text-sm"></th>
                <th class="px-4 py-3 text-sm">{{total}} Bs</th>
                <td class="px-4 py-3 text-xs">
                    <span class="px-2 py-1 font-semibold leading-tight text-red-700 bg-red-100 rounded-full dark:text-red-100 dark:bg-red-700">
                        <a href="{% url 'sales:clear_cart' %}">Eliminar</a>
                    </span>
                </td>
            </tr>
        </tbody>
      </table>
    </div>
</div>
{% render_title 'Datos del cliente' %}
<div class="px-4 py-3 mb-8 bg-white rounded-lg shadow-md dark:bg-gray-800">
    <form method="POST">
        {% csrf_token %}
        {% render_input form_client.name %}
        {% render_input form_client.nit %}
        {% render_input form_received.received %}
        {% render_button_form 'Imprimir Orden' %}
    </form>
</div>

{% else%}
{% render_title 'No hay ordenes en el carrito' %}
{% render_button 'Volvel al inicio' 'home:home' %}
{% endif %}

{% endblock %}